version: '3.8'

networks:
  mi-red:
    driver: bridge

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: centro-de-descargas
    ports:
      - "8080:8080"
    volumes:
      - ./configs/qbittorrent:/config
      - ./downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - WEBUI_USER=${QB_USER}
      - WEBUI_PASS=${QB_PASS}
    networks:
      - mi-red
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: buscador-centro-de-descargas
    ports:
      - "9117:9117"
    volumes:
      - ./configs/jackett:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - mi-red
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: gestion
    ports:
      - "9000:9000"
    volumes:
      - ./configs/portainer:/data
    networks:
      - mi-red
    restart: unless-stopped

volumes:
  portainer-data:
