version: '3.8'

networks:
  mi-red:
    driver: bridge

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8081:8080"
    volumes:
      - ./qb-config:/config
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - WEBUI_PORT=8080
    networks:
      - mi-red
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: gestion
    ports:
      - "9000:9000"
    volumes:
      - /var/run/podman/podman.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - mi-red
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: media-server
    environment:
      - TZ=America/Santiago
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin-config:/config
      - ./media:/media
    networks:
      - mi-red
    restart: unless-stopped

volumes:
  portainer-data:
